# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitUntracked < Formula
  desc "Propagate untracked files from the main worktree to other git worktrees."
  homepage "https://github.com/linyows/git-untracked"
  version "0.1.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/linyows/git-untracked/releases/download/v0.1.0/git-untracked_darwin_x86_64.tar.gz"
      sha256 "a460e74ea168ae88fb0a7dbb1608e41db7d9c1d345f07d188addda042e244bf1"

      define_method(:install) do
        bin.install "git-untracked"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/linyows/git-untracked/releases/download/v0.1.0/git-untracked_darwin_arm64.tar.gz"
      sha256 "0f43ab401166a5cfe0c0f6319000de021dae33742ef66b41ab4012000bb648c2"

      define_method(:install) do
        bin.install "git-untracked"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/linyows/git-untracked/releases/download/v0.1.0/git-untracked_linux_x86_64.tar.gz"
      sha256 "844c269f517c5fcc1a1667a30127e615f24d1e17813aafe99597f2ea664bca7c"
      define_method(:install) do
        bin.install "git-untracked"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/linyows/git-untracked/releases/download/v0.1.0/git-untracked_linux_arm64.tar.gz"
      sha256 "43671126dd4ccfce7297c1d4d7269ffc11dc86efe06b462f6084d1b78db6567e"
      define_method(:install) do
        bin.install "git-untracked"
      end
    end
  end

  test do
    system "#{bin}/git-untracked version"
  end
end
