# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitUntracked < Formula
  desc "Propagate untracked files from the main worktree to other git worktrees."
  homepage "https://github.com/linyows/git-untracked"
  version "0.2.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/linyows/git-untracked/releases/download/v0.2.0/git-untracked_darwin_x86_64.tar.gz"
      sha256 "faa0d77c175eb785b0a342e3177fb3ea618b150dc1b32ca9095991bca0643efb"

      define_method(:install) do
        bin.install "git-untracked"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/linyows/git-untracked/releases/download/v0.2.0/git-untracked_darwin_arm64.tar.gz"
      sha256 "5e73074a518a8bc66e4d84f0e15e51924955fb80da90bff7d6f7c306ef84d875"

      define_method(:install) do
        bin.install "git-untracked"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/linyows/git-untracked/releases/download/v0.2.0/git-untracked_linux_x86_64.tar.gz"
      sha256 "ea99608ac97c9429d953d2638a420f7e9276c08b83539bef7db4cdc52bea745c"
      define_method(:install) do
        bin.install "git-untracked"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/linyows/git-untracked/releases/download/v0.2.0/git-untracked_linux_arm64.tar.gz"
      sha256 "a8b6620a72fe2e86667aedf3451f90ca391581bf125154e21d00d0fd30545fcc"
      define_method(:install) do
        bin.install "git-untracked"
      end
    end
  end

  test do
    system "#{bin}/git-untracked version"
  end
end
